[package]
name = "ray-tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "*"
cgmath = "*"
derive_more = "*"
num-traits = "*"
rgb = { git = "https://github.com/ncihnegn/rust-rgb", branch = "approx" }
